# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see:
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#   https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

name: Cypress CI

on:
  # Manual button click from the GitHub UI
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:7.4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: npm install cypress --save-dev
          start: npm start
          wait-on: "http://localhost:3000"

      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
